config/routes.rb
Rails.application.routes.draw do
  resources :movies, only:[:index, :show]

  resources :search, only: [:index] do
    collection do
      get 'results'
    end 
  end  

  get 'static_about', to: 'pages#about', as: 'about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :rental

    validates :name,:email, presence: true, uniqueness: true 
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :storage, dependent: :destroy
    has_many :rental
    
    validates :imdb_id,                                presence: true, uniqueness: true
    validates :imdb_link, :title, :imdb_score, :genre, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :movie
  belongs_to :storage

  has_many :customer, dependent: :destroy

  validates :rental_date, presence: true
end

app/models/storage.rb
class Storage < ApplicationRecord
  belongs_to :movie

  has_many :rental

  validates :price,           presence: true
  validates :stock_quantity,  presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.page(params[:page]).per(12)
    @movies_search = Movie.where('title LIKE ?',  "%#{params[:q]}%")
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
      def about
      end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
        @movies_all = Movie.all
    end

    def results
        @movies = Movie.where('title LIKE ?', "%#{params[:q]}%")     
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<nav class="navbar navbar-expand-xl fixed-top navbar-dark bg-dark">

    <a class="navbar-brand" href="/">Movie Store</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse"  id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/search">Search</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/static_about">About</a>
            </li>
        </ul>    
    </div>    
</nav>

<br />
<br />
<br />
<div class="container">

<nav class="float-right mt-2">
    <ul class="pagination">
     <li class="page-item">
      <%=link_to paginate @movies %>
     </li>
    </ul> 
</nav> 

<div class="wrap">
 <h2>Movie</h2>
  <ul>
   <% @movies.each do |movie| %>
    <li>
     <img class="img-thumbnail" src=<%= movie.poster %> alt="img"  />  
     <p><%= link_to movie.title, movie %></p>
    </li>
   <% end %> 
  </ul> 
 </div> 
</div>  

app/views/movies/show.html.erb
<nav class="navbar navbar-expand-xl fixed-top navbar-dark bg-dark">

    <a class="navbar-brand" href="/">Movie Store</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse"  id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="/search">Search</a>
            </li>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="/static_about">About</a>
            </li>
        </ul>
    </div>    
</nav>

<br />
<br />
<br />
<div class="container">
<p id="notice"></p>

<div class="row">
  <div class="col-12 col-sm-6">
   <img class="img-fluid" src="<%= @movie.poster%>">
  </div> 
  
  <div class="col">
   <h2><%= @movie.title%></h2>
   <p>
    <strong>Genre: </strong>
    <%=@movie.genre%>
   </p>

   <p>
    <strong>IMDB ID: </strong>
    <%=@movie.imdb_id%>
   </p>

   <p>
    <strong>IMDB Score: </strong>
    <%=@movie.imdb_score%>
   </p>

   <p>
    <strong>IMDB Link: </strong>
    <a href="<%=@movie.imdb_link%>"><%=@movie.imdb_link%></a>
   </p>

   <% @movie.storage.each do |s| %> 
   <p>
    <strong>Price: </strong>
     $<%= s.price%>
   </p>

   <p>
    <strong>Stock Quantity: </strong>
    <%= s.stock_quantity %>
   </p> 
   <% end %>
  </div>

<br />
<br />
  <table class="table">
   <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone Number</th>
    <th>Email</th>
    <th>Rental Date</th>
   </tr>
  
  <% @movie.rental.each do |r| %>
  <% r.customer.each do |c| %>
   <tr>
    <td><%= c.name %></td>
    <td><%= c.address %></td>
    <td><%= c.phone_num %></td>
    <td><%= c.email %></td>
    <td><%= r.rental_date%></td>
   </tr>
  <% end %>
  <% end %>
  </table>
</div>  

app/views/pages/about.html.erb
<nav class="navbar navbar-expand-xl fixed-top navbar-dark bg-dark">

    <a class="navbar-brand" href="/">Movie Store</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse"  id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/search">Search</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/static_about">About</a>
            </li>
        </ul>    
    </div>    
</nav>

<br />
<br />
<br />

<div class="container">
 <h2>About</h2>
  <%= image_tag("Movie_Store.png", :alt => "Movie_Store", :class => "thumbnail")%>
  <br />
  <br />
  <p class="p_text">
    The database structure displays by the ERD picture. Every movie has the price and the number of storages, also customer can rent the movie from the movie store. Customers can have many rental info; every rental info belong to the customer. 
  </p>
  <p class="p_text">
   The data of movie is from the CSV file, call “MovieGenre.csv”, others is from faker.
  </p>
</div> 

app/views/search/index.html.erb
<nav class="navbar navbar-expand-xl fixed-top navbar-dark bg-dark">

    <a class="navbar-brand" href="/">Movie Store</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse"  id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>

            <li class="nav-item ">
                <a class="nav-link" href="/search">Search</a>
            </li>

            <li class="nav-item ">
                <a class="nav-link" href="/static_about">About</a>
            </li>
        </ul>    
    </div>    
</nav>

<br />
<br />
<br />

<div class="container">
 <h2>Search</h2>

<div class="form">
<%= form_tag(results_search_index_path, method: "get") do %>
  <%= label_tag(:q, "Search for:", :class => 'label label-info', :style => 'color: white') %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search", :class => 'btn-primary') %>
<% end %>
<div>

 <div class="container-fluid">
  <ul class="list-inline">
   <% @movies_all.each do |movie| %>
    <li>  
     <p><%= link_to movie.title, movie %></p>
    </li>
   <% end %> 
  </ul> 
  </div> 

app/views/search/results.html.erb
<nav class="navbar navbar-expand-xl fixed-top navbar-dark bg-dark">

    <a class="navbar-brand" href="/">Movie Store</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse"  id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/search">Search</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/static_about">About</a>
            </li>
        </ul>    
    </div>    
</nav>

<br />
<br />
<br />
<br />
<div class="container">
<h2>Movie Found: <%= @movies.size %></h2>

<% if @movies.empty? %>
  <p class="p_text">There is no record of movie.</p>
<% else %>
  <ul class="list-inline">
    <% @movies.each do |movie| %>
      <li><%= link_to movie.title, movie %></li>
    <% end %>
    <li><a class="nav-link" href="/search">Back to search</li>
  </ul>
<% end %>

</div>